name: Build Executables

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==6.7

      - name: Build Windows executable
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile --noconsole --icon=krakenrelay.ico --name KrakenRelay main.py

      - name: Build Unix executable
        if: matrix.os != 'windows-latest'
        run: |
          pyinstaller KrakenRelay.spec

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: KrakenRelay-${{ matrix.os }}
          path: dist/
          retention-days: 5

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
